name: Sigma

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Sigma
        run: |
          curl --output sigma_linux https://sig-repo.synopsys.com/artifactory/sigma-release-trial/latest/sigma-linux_x86_64 && \
            chmod +x sigma_linux && \
            ./sigma_linux analyze
            
      # Here is where this action is called
      - name: Parse Sigma Output
        uses: jcroall/sigma-report-output@v0.1.0
        with:
            json-file-path: ./sigma-results.json
            github-token: ${{ secrets.GITHUB_TOKEN }}
